baseURL = 'https://zigcli.liujiacai.net/'
languageCode = 'en-us'
title = 'Zigcli'
enableGitInfo = true
copyright = """
&copy; 2023-2026 Jiacai Liu. Built with <a href="https://gohugo.io/">Hugo</a> using <a href="https://www.docsy.dev/">docsy theme</a> <br>
<a href="https://github.com/jiacai2050/zigcli">Source Code</a>
"""

[params]
github_repo = 'https://github.com/jiacai2050/zigcli'
github_subdir = 'docs'
offlineSearch = true

[module]
proxy = "https://goproxy.cn,direct"
[[module.imports]]
path = "github.com/google/docsy"

[params.ui]
navbar_logo = true
showLightDarkModeMenu = true

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "pygments"
    linenos = true
