baseURL = 'https://zigcli.liujiacai.net/'
languageCode = 'en-us'
title = 'Zigcli'
enableGitInfo = true

[params]
github_repo = 'https://github.com/jiacai2050/zigcli'
github_subdir = 'docs'
offlineSearch = true

[module]
proxy = "https://goproxy.cn,direct"
[[module.imports]]
path = "github.com/google/docsy"

[params.copyright]
  authors = "Jiacai Liu | [CC BY 4.0](https://creativecommons.org/licenses/by/4.0) | "
  from_year = 2023

[params.ui]
navbar_logo = false
showLightDarkModeMenu = true

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "pygments"
    linenos = true
