name: Mirror

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  codeberg:
    if: github.repository_owner == 'jiacai2050'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Codeberg
        if: always()
        run: |
          git push --tags --force \
          https://${{ secrets.CBTOKEN }}@codeberg.org/${{ github.repository }}.git \
          "refs/remotes/origin/*:refs/heads/*"

      - name: atomgit
        if: always()
        run: |
          git push --tags --force \
          https://jiacai2050:${{ secrets.ATOMGIT_TOKEN }}@atomgit.com/${{ github.repository }}.git \
          "refs/remotes/origin/*:refs/heads/*"
