name: Release

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.zig"
      - ".github/build-release.sh"
      - ".github/workflows/CI.yml"
      - ".github/workflows/release.yml"
  push:
    branches:
      - main
    paths:
      - "**.zig"
      - ".github/workflows/release.yml"
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  upload-assets:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: aarch64-linux
          - os: ubuntu-latest
            target: x86_64-linux
          - os: ubuntu-latest
            target: x86_64-macos
          - os: ubuntu-latest
            target: aarch64-windows
          - os: ubuntu-latest
            target: x86_64-freebsd
          - os: ubuntu-latest
            target: aarch64-freebsd
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
      - name: Set env(release)
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          echo "RELEASE_VERSION=${{  github.ref_name }}" >> $GITHUB_ENV
          echo "OUT_DIR=/tmp/zigcli" >> $GITHUB_ENV
      - name: Set env(dev)
        if: "!startsWith(github.ref, 'refs/tags/')"
        shell: bash
        run: |
          echo "RELEASE_VERSION=nightly" >> $GITHUB_ENV
          echo "OUT_DIR=/tmp/zigcli" >> $GITHUB_ENV
      - name: Build
        shell: bash
        run: |
          export TARGET="${{ matrix.target }}"
          bash .github/release-single.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.OUT_DIR }}/*
      - name: Upload
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: zigcli-${{ matrix.os }}-${{ matrix.target }}
          path: ${{ env.OUT_DIR }}

  upload-assets-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
      - name: Set env(release)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          "RELEASE_VERSION=${{ github.ref_name }}" >> $env:GITHUB_ENV
          "OUT_DIR=$env:TEMP\zigcli" >> $env:GITHUB_ENV
      - name: Set env(dev)
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          "RELEASE_VERSION=nightly" >> $env:GITHUB_ENV
          "OUT_DIR=$env:TEMP\zigcli" >> $env:GITHUB_ENV
      - name: Build(Windows)
        run: |
          $git_commit = git rev-parse --short HEAD
          $build_date = Get-Date -Format "yyyy-MM-ddTHH:mm:ssK"
          New-Item -ItemType Directory -Force -Path $env:OUT_DIR
          zig build -Doptimize=ReleaseSafe `
          -Dgit_commit=$git_commit -Dbuild_date=$build_date -Dversion=$env:RELEASE_VERSION
          Remove-Item zig-out/bin/*demo
          Copy-Item LICENSE, README.org zig-out
          Compress-Archive -Path zig-out/* -DestinationPath "$env:OUT_DIR/zigcli-$env:RELEASE_VERSION-x86_64-windows.zip"
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.OUT_DIR }}/*
      - name: Upload
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: zigcli-windows-latest
          path: ${{ env.OUT_DIR }}

  upload-assets-mac:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
      - name: Set env(release)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "RELEASE_VERSION=${{  github.ref_name }}" >> $GITHUB_ENV
          echo "OUT_DIR=/tmp/zigcli" >> $GITHUB_ENV
      - name: Set env(dev)
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          echo "RELEASE_VERSION=nightly" >> $GITHUB_ENV
          echo "OUT_DIR=/tmp/zigcli" >> $GITHUB_ENV
      - name: Build(MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          export GIT_COMMIT=$(git rev-parse --short HEAD)
          export BUILD_DATE=$(date +'%Y-%m-%dT%H:%M:%S%z')
          mkdir -p "${OUT_DIR}"
          zig build -Doptimize=ReleaseSafe -Dcpu=apple_m1 \
          -Dgit_commit=${GIT_COMMIT} -Dbuild_date=${BUILD_DATE} -Dversion=${RELEASE_VERSION}
          rm -f zig-out/bin/*demo
          cp LICENSE README.org zig-out
          find zig-out
          pushd zig-out
          zip -r ${OUT_DIR}/zigcli-${RELEASE_VERSION}-aarch64-macos.zip .
          popd
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.OUT_DIR }}/*
      - name: Upload
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: zigcli-${{ matrix.os }}
          path: ${{ env.OUT_DIR }}
